### ISSUE TITLE
*.js must be minified

### ISSUE THREAD

**Issue by mmaayylliiss** [wearemd/static-site-starter#4]

**Comment by Awea** [comment]
@mmaayylliiss *.js is already minified when you use `make build`.

**Comment by mmaayylliiss** [comment]
@Awea HTML/CSS are minified while we `make serve`. Why JavaScript isn’t?

**Comment by Awea** [comment]
@mmaayylliiss There is no particular reason for HTML/CSS to be minified in development. The JavaScript is not minified to enhance the debugging process (open the console and you'll see what I mean).

**Comment by mmaayylliiss** [comment]
> There is no particular reason for HTML/CSS to be minified in development.

@Awea Ok so let’s unminify HTML/CSS in dev, no?

**Comment by Awea** [comment]
@mmaayylliiss Unminifying HTML will require an extra gulp plugin (https://github.com/Awea/gulp-pretty-html for example) and I think that there is no point to it. And CSS supports sourcemap with compressed output so it's already developer friendly.

**Comment by mmaayylliiss** [comment]
@Awea Alright so I close the issue
